language: generic
 
sudo: required
 
services:
  - docker

script:
  - docker build -t damienpond/flask-test .

after_success:
  - docker build -t damienpond/flask-test .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push damienpond/flask-test 