# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'docker_hub'
    repository: 'azure_test'
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'docker_hub'
    repository: 'azure_test'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'docker_hub'
    repository: 'azure_test'
    command: 'push'
- task: Docker@2
  inputs:
    containerRegistry: 'docker_hub'
    repository: 'azure_test'
    command: 'logout'
